version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "textract-sample"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-yok208j11tol"
s3_prefix = "textract-sample"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
disable_rollback = true
